site_name: WEPP
repo_name: TurakhiaLab/WEPP
repo_url: https://github.com/TurakhiaLab/WEPP

theme:
  name: material

  logo: images/WEPP_icon.png
  favicon: images/WEPP_icon.png
  features:
    # - announce.dismiss
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tooltips
    - toc.follow
    - toc.integrate
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.tabs.sticky
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.footer
    - navigation.expand
    - search.highlight
    - search.suggest
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal   
      accent:  pink

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: teal
      accent: pink

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TurakhiaLab/WEPP

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

use_directory_urls: false
nav:
  - Home: index.md